### PR TITLE
Feat/bac 46 location

### PR DESCRIPTION
**Pull request by Lawkay1**
Response modification

### CODE REVIEW

**Comment by devvspaces** [comment]
What did you add sir? You did not specify the actual modification. Please do

**Comment by devvspaces** [comment]
I ran some tests on your code, and it's actually running perfectly

**Comment by Lawkay1** [comment]
I added the latitude and longitude to the response of the /location endpoint as specified by the mobile developer. i also made some minor tweaks to the /weather/forecast/tomorrow/immediate endpoint so it can give a valid response.

**Comment by devvspaces** [comment]
Okay, you can create a new PR, correctly stating that and send me the link so i can check it. Thanks @Lawkay1

**Pull request merged**
